"""initial schema

Creates the pgvector extension and the full v1 schema from SQLAlchemy metadata,
plus retrieval indexes and the tsvector trigger that Alembic autogenerate cannot
express. Subsequent migrations are ordinary autogenerated diffs.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-06
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.config import get_settings
from app.models import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DIM = get_settings().embedding_dim


def upgrade() -> None:
    bind = op.get_bind()
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    Base.metadata.create_all(bind)

    # Hybrid-retrieval indexes (not expressible via the ORM model).
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_code_chunks_embedding "
        "ON code_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_code_chunks_tsv ON code_chunks USING gin (tsv)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_code_chunks_symbol_trgm "
        "ON code_chunks USING gin (symbol gin_trgm_ops)"
    )

    # Keep tsv in sync with content + symbol.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION code_chunks_tsv_refresh() RETURNS trigger AS $$
        BEGIN
          NEW.tsv :=
            setweight(to_tsvector('english', coalesce(NEW.symbol, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(NEW.content, '')), 'B');
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute("DROP TRIGGER IF EXISTS trg_code_chunks_tsv ON code_chunks")
    op.execute(
        "CREATE TRIGGER trg_code_chunks_tsv BEFORE INSERT OR UPDATE OF content, symbol "
        "ON code_chunks FOR EACH ROW EXECUTE FUNCTION code_chunks_tsv_refresh()"
    )


def downgrade() -> None:
    bind = op.get_bind()
    op.execute("DROP TRIGGER IF EXISTS trg_code_chunks_tsv ON code_chunks")
    op.execute("DROP FUNCTION IF EXISTS code_chunks_tsv_refresh()")
    Base.metadata.drop_all(bind)
